### ISSUE TITLE
Add filtering of observational data to 95-99% density envelope

### ISSUE THREAD

**Issue by jcoliver** [Big-Biodiversity-Collaborative/SwallowtailClimateChange#35]
Want to systematically filter observational data before analyses to get rid of outliers (e.g. east coast _P. rumiko_). Something like creating a density envelop and ditching anything outside that envelope.

**Comment by ezylstra** [comment]
@jcoliver Looking at changes made to the data-gbif-qa.R script - looks great!  One question did occur to me: are we okay with deleting those 2% of observations permanently?  I ask because in theory, this script would only be run once (after downloading data from gbif) and would then put all the filtered data files into gbif.zip.  If we think there's any chance we may want to access all the gbif observations at some later point, we could put this section of code in a create-pa-datasets.R script.  That script could grab original gbif data from the zip folder, do all the filtering we want (including the density envelope), add background points, add current predictor values, and put resulting presence-absence datasets into a new zip folder (eg, presence-absence.zip). Not sure if one option is better or not, but thought I'd ask the question.

**Comment by jcoliver** [comment]
Yeah, I'm thinking we need to leave the gbif files as they are, with zero filtering, and create a separate directory ("filtered-gbif"?).

An aside: the approach mostly works, but for widespread species it fails miserably because we hit the lower limit of R's precision. resulting in too many cells with a density estimate of 0. Will try a higher precision implementation next.

**Comment by jcoliver** [comment]
Yeah, I'll use the work you have done in the development folder to guide how I create those directories.

Filtering theoretically is fine, it's just that R considers 0.000000000000000000000001 to be equal to 0. Which, in some cases, it is not. :D

**Comment by ezylstra** [comment]
Ugghhh.

**Comment by jcoliver** [comment]
Fixed "precision" issue, which was actually caused by some species with very high density of observations in a small area (e.g. _Fraxinus pennsylvanica_). Addressed by creating a thinned data set of observations (sampling only 1 obs per cell of climate data) and using that thinned data for kernel density estimates. See d73a92c et al.
