### ISSUE TITLE
Add thinning approach to observational data

### ISSUE THREAD

**Issue by jcoliver** [Big-Biodiversity-Collaborative/SwallowtailClimateChange#36]
To address sampling bias, could thin data using approaches like the one referenced in [Streito et al. 2021](https://doi.org/10.1038/s41598-021-90378-1) (see Methods, Environmental Filtering and reference 52 [Varela et al. 2014](https://doi.org/10.1111/j.1600-0587.2013.00441.x)).

**Comment by jcoliver** [comment]
Check out the spThin package

+ On GitHub: https://github.com/mlammens/spThin
+ _Ecography_ paper: https://doi.org/10.1111/ecog.01132

**Comment by ezylstra** [comment]
Start by removing what are likely duplicate occurrence records in our data filtering script. Try something using distinct() based on the date, lat, and long.

**Comment by ezylstra** [comment]
Edited gbif-2-filter.R to remove duplicate locations (see 766f49f). Note: Didn't run and create new gbif-filtered.zip.  

Next step, assuming we thin occurrence records by sub-sampling grid cells (at resolution of climate data): explore how the choice of sampling 1 point vs multiple points could affect inferences.

**Comment by ezylstra** [comment]
- Modified gbif-2-filter.R to make the thinning process generalizable. Now can thin occurrence records based on grid cells (in climate raster) by specifying the maximum number of records retained in each cell (see 0d739a4). 
- There's no longer a need to remove duplicates (with above changes), so stuck that from script.
- For now, keeping just one observation per grid cell because that's consistent with many SDM approaches and packages (like ENMeval).  
Can always go back and evaluate how the choice of sampling 1 point vs multiple points per cell could affect inferences, but maybe close this comment for now?
