### ISSUE TITLE
Reduce size of BRT model objects

### ISSUE THREAD

**Issue by ezylstra** [Big-Biodiversity-Collaborative/SwallowtailClimateChange#41]
BRT models (gbm objects) are very big because each model stores information about 1000s of trees. This means the resulting species-specific .rds files we want to create can be many MB (e.g., output/SDMs/papilio_rumiko-BRT.rds is ~16 MB).  Zipping these files doesn't compress things much at all.  Need to figure out if there's a way to reduce the size of the model objects and/or whether it's worth keeping BRT SDMs in the mix.

**Comment by jcoliver** [comment]
Indeed. This prompts a larger discussion we should have about storage/management of model output for _all_ approaches. Right now it's "disposable" in that we don't track any of it with Git (in part because I hate dealing with Git LFS), but we should probably think about a better way of managing those model outputs...

**Comment by ezylstra** [comment]
And for the record, I think the size of RF model objects are considerably bigger than BRT...

**Comment by jcoliver** [comment]
Closing for now, accepting the size of BRT/RF objects and using non-GitHub remote storage options for sharing model output. See #51 .
