### ISSUE TITLE
Add option to use equal area projection for overlap/delta maps?

### ISSUE THREAD

**Issue by ezylstra** [Big-Biodiversity-Collaborative/SwallowtailClimateChange#89]
When looking at maps for some species with large geographic ranges (eg, P. machaon), I'm thinking we might want to use a different projection for maps because things start looking crazy. I think I've worked out most of the kinks, but the kicker is that the terra::project() function is REALLY slow for large rasters. My current thought is that we add an argument to the map functions that would indicate when we want to use the Equal Area Albers projection. Haven't added anything to repo - I think it's best to chat about this before adding the functionality.

**Comment by jcoliver** [comment]
Great point about adding the functionality to the map functions. We could also have an "auto" option, that picks the best projection based on the size / geographic location of the map. That is, for large maps (or those mostly in the north?), the "auto" option would be the EAA, and for less extreme maps the "auto" option would be whatever we currently use. So an argument definition might look something like:

`project = c("auto", "albers", "<name of whatever projection we currently use>")`

So by default the projection is auto(matically) selected, but we still maintain functionality for the user to override the projection if they so choose. This suggestion _does_ rely on us being able to programmatically determine which projection is "best" from the raster alone (maybe a calculation of the area or maximum latitude?).

**Comment by ezylstra** [comment]
Hey @jcoliver.  I like your idea. One last question before trying to implement something like that: If we use an "auto" option, we can potentially end up with 5 overlap maps for one species that have different projections (because the future prediction area is bigger than the current prediction area). Problem?  Or just go back and run things after overriding with project = X if we encounter that situation?

**Comment by ezylstra** [comment]
Added a projection argument (auto, latlon, or lambert) to `overlap_map` function in 40a4dbd6. I also removed the boundaries argument because it made the function much more complicated and I couldn't imagine a scenario when we wouldn't want political boundaries in a mamp.

**Comment by jcoliver** [comment]
Good point about the issue with different projections for different time periods / climate models. I envision most comparisons would be _within_ a species, so it would be ideal to have the same projection used for all five maps. Buuuuuut, since we're calling one map at a time, using the "auto" option seems like a good way to get to the not ideal spot of having different projections for different scenarios. I think we could still keep the "auto" functionality as default, but in practice, check all five of the incoming rasters to determine if any will need the EAA projection. If at least one does, we use `project = "EAA"`, otherwise we use `project = "<normal projection>"`). This switches the iteration approach a bit (but might make it easier to package stuff into a `list` and use something in the `lapply()` family).
