### ISSUE TITLE
Update forecast data to explicitly use 8-model ensemble

### ISSUE THREAD

**Issue by jcoliver** [Big-Biodiversity-Collaborative/SwallowtailClimateChange#96]
Links to forecast data have been updated at [https://adaptwest.databasin.org/pages/adaptwest-climatena/](https://adaptwest.databasin.org/pages/adaptwest-climatena/) to use mean values from 8 or 13 different models. Need to update src/data/prep-forecast-data.R to explicitly use the ~13-model~ 8-model ensemble.

**Comment by ezylstra** [comment]
@jcoliver Sounds like it might be better to use the 8-model ensemble because of info and resources linked on the website noted above. Specifically they state: _Consistent with the guidance provided by Hausfather et al. (2022), users wishing to use an ensemble mean projection are encouraged to use the 8-model rather than the 13-model ensemble mean. In addition, users of the individual model projections are advised to exclude UKESM1-0 from ensemble analysis. Further rationale for this guidance and a comparison of the 8 and 13-model ensembles is available [here](https://s3-us-west-2.amazonaws.com/www.cacpd.org/webcontent/ClimateNA_8ModelRationale_Mahony_07May2022.pdf)._

**Comment by jcoliver** [comment]
Addressed in [db71171](https://github.com/Big-Biodiversity-Collaborative/SwallowtailClimateChange/commit/db71171c087cdf246607260312de39ee8c98c357).
